# Generated by Django 5.2.9 on 2025-12-04 04:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor')], max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('forma_pago', models.CharField(blank=True, choices=[('contado', 'Contado'), ('cuenta corriente', 'Cuenta Corriente')], max_length=50)),
                ('dias_cc', models.IntegerField(default=0)),
                ('saldo_contacto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('categoria', models.CharField(blank=True, choices=[('Mayorista', 'Mayorista'), ('Minorista', 'Minorista')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro', models.CharField(choices=[('pollo entero', 'Pollo Entero'), ('trozados y derivados', 'Trozados y Derivados'), ('prefritos', 'Prefritos'), ('elaborados', 'Elaborados'), ('huevos', 'Huevos'), ('panificados', 'Panificados'), ('vegetales', 'Vegetales'), ('cerdo', 'Cerdo')], max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('un', 'Unidad')], max_length=20)),
                ('precio_minorista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_mayorista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateField(default=django.utils.timezone.now, null=True)),
                ('actualizado_en', models.DateField(auto_now=True, null=True)),
                ('es_oferta', models.BooleanField(default=False)),
                ('fecha_inicio_oferta', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_oferta', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('forma_pago', models.CharField(choices=[('cuenta corriente', 'Cuenta Corriente'), ('contado', 'Contado')], max_length=50)),
                ('estado_pago', models.CharField(default='pendiente', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(limit_choices_to={'tipo': 'proveedor'}, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='core.contactos')),
            ],
            options={
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='Cobros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cobro', models.DateTimeField(default=django.utils.timezone.now)),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='cobros', to='core.contactos')),
            ],
            options={
                'ordering': ['-fecha_cobro'],
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(limit_choices_to={'tipo': 'proveedor'}, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.contactos')),
            ],
            options={
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='PagosDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_detalle', to='core.compras')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pagos')),
            ],
            options={
                'verbose_name': 'Detalle de Pago',
                'verbose_name_plural': 'Detalles de Pagos',
            },
        ),
        migrations.CreateModel(
            name='PedidosCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('cancelado', 'Cancelado'), ('recibido', 'Recibido')], default='pendiente', max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(limit_choices_to={'tipo': 'proveedor'}, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_compras', to='core.contactos')),
            ],
        ),
        migrations.AddField(
            model_name='compras',
            name='pedido_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='core.pedidoscompras'),
        ),
        migrations.CreateModel(
            name='PedidosVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('direccion_entrega', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], default='pendiente', max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('aclaraciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, to='core.contactos')),
            ],
            options={
                'verbose_name': 'Pedido de Venta',
                'verbose_name_plural': 'Pedidos de Venta',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='PedidosVentasDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pedidosventas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productos')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido de Venta',
                'verbose_name_plural': 'Detalles de Pedidos de Venta',
            },
        ),
        migrations.CreateModel(
            name='PedidosComprasDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pedidoscompras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productos')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido de Compra',
                'verbose_name_plural': 'Detalles de Pedidos de Compra',
            },
        ),
        migrations.CreateModel(
            name='ComprasDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.compras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(default=django.utils.timezone.now)),
                ('direccion_entrega', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_reprogramada', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_entrega', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('forma_pago', models.CharField(choices=[('CC', 'Cuenta Corriente'), ('CO', 'Contado'), ('CP', 'Contado Pendiente')], max_length=50)),
                ('estado_entrega', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='pendiente', max_length=20)),
                ('estado_cobro', models.CharField(choices=[('pendiente', 'Pendiente'), ('cobrado', 'Cobrado'), ('parcial', 'Parcial')], default='pendiente', max_length=20)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'tipo': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='core.contactos')),
                ('pedido_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='core.pedidosventas')),
            ],
            options={
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.AddField(
            model_name='pedidoscompras',
            name='ventas_relacionadas',
            field=models.ManyToManyField(blank=True, related_name='pedidos_compras', to='core.ventas'),
        ),
        migrations.CreateModel(
            name='CobrosDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.cobros')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros_detalle', to='core.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='VentasDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.ventas')),
            ],
        ),
    ]
