# Generated by Django 5.2.9 on 2025-12-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactos',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
