# Generated by Django 5.2.9 on 2025-12-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactos_nombre_fantasia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_mayorista',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_minorista',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
