# Generated by Django 5.2.9 on 2025-12-04 04:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productos_precio_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosventas',
            name='actualizado_en',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedidosventas',
            name='creado_en',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='pedidosventas',
            name='fecha_pedido',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='productos',
            name='creado_en',
            field=models.DateField(default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='fecha_fin_oferta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='fecha_inicio_oferta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
