# Generated by Django 5.2.9 on 2025-12-04 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pedidosventas_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobros',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='cobros',
            name='fecha_cobro',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='compras',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='compras',
            name='fecha_compra',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='pedidoscompras',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='pedidoscompras',
            name='fecha_pedido',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='pedidosventas',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pedidosventas',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha_venta',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
