# Generated by Django 5.2.9 on 2025-12-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cobros_creado_en_alter_compras_creado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosventas',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
