# Generated by Django 5.2.9 on 2025-12-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pedidosventas_fecha_cancelacion_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='fecha_cancelacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='estado_cobro',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cobrado', 'Cobrado'), ('parcial', 'Parcial'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
