# Generated by Django 5.2.9 on 2025-12-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ventas_fecha_cancelacion_ventas_motivo_cancelacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='forma_pago',
            field=models.CharField(choices=[('cuenta corriente', 'Cuenta Corriente'), ('contado', 'Contado'), ('contado pendiente', 'Contado Pendiente')], max_length=50),
        ),
    ]
