# Generated by Django 5.2.9 on 2025-12-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ventas_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='estado_compra',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='compras',
            name='fecha_cancelacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventas',
            name='estado_venta',
            field=models.CharField(choices=[('en proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='en proceso', max_length=20),
        ),
    ]
