# Generated by Django 5.2.9 on 2025-12-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_compras_estado_compra_compras_fecha_cancelacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
