# Generated by Django 5.2.9 on 2025-12-13 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_compras_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoscompras',
            name='ventas_relacionadas',
        ),
        migrations.AddField(
            model_name='ventas',
            name='pedido_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='core.pedidoscompras'),
        ),
    ]
