# Generated by Django 5.2.9 on 2025-12-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_pedidoscompras_ventas_relacionadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Parcial'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
