# Generated by Django 5.2.9 on 2025-12-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_compras_estado_pago_alter_usuarios_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasdetalle',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='cobros',
            name='saldo_disponible',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='compras',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='saldo_disponible',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedidoscompras',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedidoscomprasdetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedidosventas',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedidosventasdetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='estado_cobro',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('cobrado', 'Cobrado'), ('parcial', 'Parcial'), ('cancelado', 'Cancelado')], default='pendiente', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='cobros',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_disponible__gte', 0)), name='saldo_disponible_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='compras',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_pendiente__gte', 0)), name='compra_saldo_pendiente_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pagos',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_disponible__gte', 0)), name='pago_saldo_disponible_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='ventas',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_pendiente__gte', 0)), name='saldo_pendiente_no_negativo'),
        ),
    ]
