# Generated by Django 5.2.9 on 2025-12-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_notascredito_notascreditoaplicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notascredito',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
