# Generated by Django 5.2.9 on 2025-12-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notascredito_numero_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
