# Generated by Django 5.2.9 on 2025-12-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_compras_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
