# Generated by Django 5.2.9 on 2026-01-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_contactos_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Mayorista Exclusivo', 'Mayorista Exclusivo'), ('Mayorista', 'Mayorista'), ('Minorista', 'Minorista')], max_length=20),
        ),
    ]
