# Generated by Django 5.2.9 on 2026-01-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_contactos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio_mayorista_exclusivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
