# Generated by Django 5.2.9 on 2026-03-04 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_productos_precio_mayorista_exclusivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='pedido_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='core.pedidosventas'),
        ),
    ]
