# Generated by Django 5.2.9 on 2026-03-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_productos_unidad_medida_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventas',
            options={'ordering': ['fecha_entrega', 'orden_entrega', '-fecha_venta']},
        ),
        migrations.AddField(
            model_name='ventas',
            name='orden_entrega',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('un', 'Unidad'), ('caja', 'Caja'), ('maple', 'Maple')], max_length=20),
        ),
    ]
