# Generated by Django 5.2.9 on 2026-03-24 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_ventas_options_ventas_orden_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobros',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='', max_length=50),
        ),
        migrations.CreateModel(
            name='CobrosMedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='core.cobros')),
            ],
            options={
                'verbose_name': 'Medio de pago de cobro',
                'verbose_name_plural': 'Medios de pago de cobros',
            },
        ),
        migrations.CreateModel(
            name='PagosMedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios_pago', to='core.pagos')),
            ],
            options={
                'verbose_name': 'Medio de pago de pago',
                'verbose_name_plural': 'Medios de pago de pagos',
            },
        ),
    ]
