# Generated by Django 5.2.9 on 2026-06-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_cobros_medio_pago_alter_pagos_medio_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='pedido_compra',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='pedido_compra',
        ),
        migrations.RemoveField(
            model_name='pedidoscomprasdetalle',
            name='pedido_compra',
        ),
        migrations.RemoveField(
            model_name='pedidoscomprasdetalle',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='pedidosventas',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='pedido_venta',
        ),
        migrations.RemoveField(
            model_name='pedidosventasdetalle',
            name='pedido_venta',
        ),
        migrations.RemoveField(
            model_name='pedidosventasdetalle',
            name='producto',
        ),
        migrations.AlterModelOptions(
            name='ventas',
            options={'ordering': ['-fecha_venta']},
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='estado_entrega',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='fecha_reprogramada',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='orden_entrega',
        ),
        migrations.AlterField(
            model_name='ventas',
            name='estado_venta',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_camino', 'En Camino'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.DeleteModel(
            name='PedidosCompras',
        ),
        migrations.DeleteModel(
            name='PedidosComprasDetalle',
        ),
        migrations.DeleteModel(
            name='PedidosVentas',
        ),
        migrations.DeleteModel(
            name='PedidosVentasDetalle',
        ),
    ]
